Create cart page
yasmin-araujo/OnlineStoreWebProject pull request #7
Opened 2023-06-10 18:05 UTC by flaviosalles3

PR to add the cart page, payment information component and cart individual product component

2023-06-10 20:31 UTC, yasmin-araujo requested changes

2023-06-10 20:31 UTC, yasmin-araujo commented on van-gogh-online-webstore/src/components/NumberTextField/index.jsx
> +export default function NumberTextField({ label, value, setValue, style, min = 0, max = 100}) {
Não acho que máximo 100 é o suficiente pro componente de forma genérica, exemplo: Nos filtros eu uso esse componente pra filtrar pelos preços, e pode ser que tenhamos produtos de mil reais, etc.

Talvez dê pra deixar como undefined ou algo assim?

2023-06-10 20:31 UTC, yasmin-araujo commented on van-gogh-online-webstore/src/components/CartProduct/style.css
> +button{
Não é muito bom deixar o seletor desse jeito se a ideia é que esse estilo se aplique apenas no botão específico da página do carrinho. Muitas vezes o css acaba "vazando" entre os arquivos mesmo que você não importe no js.

Então eu iria sugerir deixar mais específico colocando um nome de classe ou referenciando a classe pai, algo assim.

2023-06-10 20:31 UTC, yasmin-araujo commented on van-gogh-online-webstore/src/components/PaymentInformations/style.css
> +button{
Mesma coisa aqui

2023-06-11 00:58 UTC, tiagocbr requested changes

2023-06-11 00:58 UTC, tiagocbr commented on van-gogh-online-webstore/src/components/PaymentInformations/index.jsx
> +			<TextField label={'Name on card'} variant='outlined' margin='normal' size='small' defaultValue={'Name'} />
Acho que ao invés de vc definir defaultValue para os campos seria melhor colocar o atributo placeholder,visualmente fica melhor,e além disso nao precisa apagar todo o campo pra começar a escrever os seus dados

2023-06-11 14:15 UTC, flaviosalles3 commented on van-gogh-online-webstore/src/components/NumberTextField/index.jsx
> +export default function NumberTextField({ label, value, setValue, style, min = 0, max = 100}) {
Perfeito eu tinha esquecido da possibilidade do undefined kk

2023-06-11 14:28 UTC, flaviosalles3 commented on van-gogh-online-webstore/src/components/PaymentInformations/index.jsx
> +			<TextField label={'Name on card'} variant='outlined' margin='normal' size='small' defaultValue={'Name'} />
Boa, ficou bem melhor mesmo

2023-06-11 17:30 UTC, tiagocbr approved these changes

2023-06-12 01:43 UTC, yasmin-araujo approved these changes

2023-06-12 01:44 UTC, merged